sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username:
    password:
  alioss:
    endpoint:
    access-key-id:
    access-key-secret:
    bucket-name:
  redis:
    host: localhost
    port: 6379
    password:
    database: 10
  wechat:
    appid:
    secret:
    mchid:
    mch-serial-no:
    private-key-file-path:
    api-v3-key:
    we-chat-pay-cert-file-path:
    notify-url:
    refund-notify-url: