sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username:
    password:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key:
    # 设置jwt过期时间
    admin-ttl:
    # 设置前端传递过来的令牌名称
    admin-token-name:
    user-secret-key:
    user-ttl:
    user-token-name:
  alioss:
    endpoint:
    access-key-id:
    access-key-secret:
    bucket-name:
  redis:
    host: localhost
    port: 6379
    password:
    database: 10
  wechat:
    appid:
    secret:
    mchid:
    mch-serial-no:
    private-key-file-path:
    api-v3-key:
    we-chat-pay-cert-file-path:
    notify-url:
    refund-notify-url: